apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment-transfers
    environment: Development
  name: payment-transfers
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: payment-transfers
  sessionAffinity: None
  type: ClusterIP
